### ISSUE TITLE
Support Telepen barcodes for reading and writing

### ISSUE THREAD

**Issue by cpwood** [rxing-core/rxing#38]
The Telepen barcode format is a widely-used format in the United Kingdom, especially in public libraries. The symbology is defined as per [this document](https://advanova.co.uk/wp-content/uploads/2022/05/Barcode-Symbology-information-and-History.pdf).

For a voluntary project to support UK libraries, I need to be able to read Telepen barcodes. With no existing open source libraries supporting this, I have now implemented Telepen in my [fork](https://github.com/cpwood/rxing) of rxing and would like to add this back to the main codebase. Ultimately, I really want to make use of these changes within the WASM implementation.

There are two variants of Telepen: alphanumeric and numeric. Numeric is _actually_ just an interpretation of the ASCII alphanumeric data returned after interpreting the barcodes, so this is left as an exercise for the user, however I can provide code samples. As such, only alphanumeric is implemented.

I appreciate this would create a divergence between zxing and rxing in that rxing would then support a wider range of symbologies, so I wanted to sound you out on whether the changes in my fork would be a welcome addition or not before we get to the pull request stage. 

I'm also a fairly new Rust programmer (though a developer more generally for many years), so there may be some things people would like me to change in the code I've written. That said, there are no compiler warnings, etc, in the code and all new code has supporting tests that pass.

Is this a change you would welcome into rxing?

**Comment by hschimke** [comment]
@cpwood I'm absolutely interested in bringing your fork into rxing. Telepen seems like a perfect addition.

I have a couple thoughts before we do a PR:

* You have a TelepenCommon struct in src/oned/telepen_common.rs. The rust way to do this is likely with a module rather than a struct.

* If possible I'd like a handful more test images, perhaps around 10.

* Please add a unit test for the telegen checksum function in TelepenCommon

* > There are two variants of Telepen: alphanumeric and numeric. Numeric is actually just an interpretation of the ASCII alphanumeric data returned after interpreting the barcodes, so this is left as an exercise for the user, however I can provide code samples. As such, only alphanumeric is implemented. 

   If you wanted to offer the ability to decode either based on expectation, you could add this through the DecodeHints enum. Not required, of course, just an option if you thought that the functionality was useful to include.

I think, given the content of this, I'd roll it up into the next release (v0.5). I have a change to the features list that I was planning to include in that release as well.

Thanks for your submission, I look forward to the PR.

**Comment by cpwood** [comment]
@hschimke Thank you for all the suggestions. Happy to work on all of those; give me a few days and I'll come back to you. In the meantime, have a Happy New Year!

**Comment by cpwood** [comment]
@hschimke I've now done the changes you requested.

1. `telepen_common.rs` is now a mod;
2. There are now 12 test cases overall: 
  * 5 alphanumeric tests
  * 7 numeric tests
  * Numeric decoding has been supported as you suggested, by introducing a hint. 
  * The additional test imagery are real photos taken at my local library today, as opposed to computer-generated bitmaps.
3. Unit tests now exist for the checksum function, and also for the _alpha -> numeric_ and _numeric -> alpha_ routines in there too.

All tests pass.

As per previous comments, it's the same code for alphanumeric and numeric, it's just there's a conversion from ASCII to numeric that happens _after_ the barcode decoding is complete with numeric. In essence, therefore, the 7 numeric tests _also_ test the alphanumeric functionality too. 

Will leave it with you to review! Let me know if you need anything further?

**Comment by hschimke** [comment]
Looks ready for a PR! I didn't see anything looking through just now but I'll do a proper review on the PR.

**Comment by hschimke** [comment]
Merged, it's been a pleasure working with you!

**Comment by cpwood** [comment]
> Merged, it's been a pleasure working with you!

Likewise! I really appreciated the time you took to point me in the right direction! Looking forward to the 1.5 WASM build!

**Comment by hschimke** [comment]
Built and published as [v0.2.0](https://www.npmjs.com/package/rxing-wasm).

I tested and verified that it is decoding Telepen with the demo site https://scan.rxing.org (which uses the latest version of the npm package)
