### ISSUE TITLE
The multiple barcodes decoder issue

### ISSUE THREAD

**Issue by xdm67x** [rxing-core/rxing#48]
Hi, when I want to decode an image containing multiples barcodes, it's not working as expected, the first and second barcodes are detected (datamatrix) but the third one is not found.

Here is the image I used to test it.

![multiple_barcodes](https://github.com/rxing-core/rxing/assets/77287913/2b3ffe34-1067-48c9-8663-f841b5d0acf6)

Thanks!

**Comment by hschimke** [comment]
I'll look into this

**Comment by hschimke** [comment]
I think that I found the issue, it's a problem with how the `GenericMultipleBarcodeReader` works.

The issue is: the mechanism to make sure that a barcode hasn't already been found isn't particularly good (it only detects whether they have the same data). In the example above I believe that two of the barcodes have the same data, so it was erroneously removing one of them from the list of results. I'm working on a fix, which should make its way into the next release.

**Comment by xdm67x** [comment]
Thanks for the fast response 😄 I will check your fix and keep you updated.

**Comment by xdm67x** [comment]
It's working thanks for the fix!
