### ISSUE TITLE
Multiple barcode decoder issue

### ISSUE THREAD

**Issue by TonyMasson** [rxing-core/rxing#51]
Hello, 

First of all, thank you for all the work you have done. 

I am encountering an issue with the detection of multiple DataMatrix codes in an image.

In the image below, we get an error of type `Err(NotFoundException(""))` because the first DataMatrix code in the image is, I believe, detected but is blurry on its right side (you can see it clearly by zooming in). However, the second DataMatrix code is good but not detected.

![BAD](https://github.com/user-attachments/assets/8e3b9d66-d114-41ca-a8e0-f1332d111827)

If I swap the two DataMatrix codes, the first one is detected and everything works as expected.
![GOOD](https://github.com/user-attachments/assets/1e8b67a7-0994-46fb-bd86-a5f3cd79f0e5)

Thank you very much.

**Comment by hschimke** [comment]
I'll look into this. I'm out of office until next week, but I'll try to provide an update by midweek.

**Comment by hschimke** [comment]
Stepping through the detection logic it appears that you are correct. There is just enough distortion that one of the symbols fails error correction. 

The issue is that the datamatrix detector, unlike the qr detector, only returns a single possible symbol. For "multiple detection" this is usually fine because the image is then chopped up and rescanned, but in this particular case that does not occur and so only one symbol in the entire image is ever parsed. I have updated the logic of the detector to return all possible symbol locations and to iterate over them. This has a slight reduction in performance in some cases, but overall should result in better detection results.

I have a working fix in testing.

**Comment by TonyMasson** [comment]
🙏 Thanks

**Comment by hschimke** [comment]
This release has been published to crates.io and to rxing-wasm v0.2.9
